[theme]
primaryColor = "#FFD700"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
